Algoritmo "Sucessor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Um programa de sucessor
// Autor(a)    : Karoline Souza
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis
numero1:inteiro
numero2:inteiro
soma:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva ("Digite um número")
leia (numero1)
soma<-numero1+1)
escreva("O sucessor é:",soma)

Fimalgoritmo